version: '3.8'
services:
  mlflow:
    build: ./mlflow
    ports:
      - "5000:5000"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
